// benchmarks/apps/hn-nuxt/app/pages/story/[id].vue
<script setup lang="ts">
import { fetchStoryWithComments, timeAgo, hostName } from '../../../../hn-shared/api';

const route = useRoute();
const id = Number(route.params.id);

const data = await fetchStoryWithComments(id);
if (!data) {
  throw createError({ statusCode: 404, statusMessage: 'Story not found' });
}

const { story, comments } = data;
</script>

<template>
  <HnHeader />
  <main class="hn-main">
    <div class="story-detail">
      <div>
        <span class="upvote"></span>
        <span class="story-title">
          <a v-if="story.url" :href="story.url">{{ story.title }}</a>
          <span v-else>{{ story.title }}</span>
          <span v-if="story.url" class="story-domain">({{ hostName(story.url) }})</span>
        </span>
      </div>
      <div class="story-meta">
        {{ story.score }} points by
        <NuxtLink :to="`/user/${story.by}`">{{ story.by }}</NuxtLink>
        {{ timeAgo(story.time) }} |
        {{ story.descendants ?? 0 }} comments
      </div>
      <div v-if="story.text" class="story-text" v-html="story.text"></div>
    </div>

    <div class="comment-section">
      <ul v-if="comments.length" class="comment-tree">
        <CommentNode
          v-for="comment in comments"
          :key="comment.id"
          :comment="comment"
          :depth="0"
        />
      </ul>
      <p v-else class="hn-empty">No comments yet.</p>
    </div>
  </main>
</template>

// benchmarks/apps/hn-nextjs/app/story/[id]/page.tsx
import { fetchStoryWithComments, timeAgo, hostName } from '../../../../hn-shared/api';
import { topStoryIds, askStoryIds, showStoryIds } from '../../../../hn-shared/fixture-ids';
import { HnHeader, CommentNode } from '../../components';

export async function generateStaticParams() {
  const allIds = new Set([...topStoryIds, ...askStoryIds, ...showStoryIds]);
  return Array.from(allIds).map((id) => ({ id: String(id) }));
}

export default async function StoryPage({
  params,
}: {
  params: { id: string };
}) {
  const result = await fetchStoryWithComments(Number(params.id));
  if (!result) {
    return (
      <>
        <HnHeader />
        <main className="hn-main">
          <div className="hn-empty">Story not found.</div>
        </main>
      </>
    );
  }
  const { story, comments } = result;
  const host = hostName(story.url);

  return (
    <>
      <HnHeader />
      <main className="hn-main">
        <div className="story-detail">
          <div className="story-title">
            <span className="upvote" />
            <a href={story.url ?? '#'}>{story.title}</a>
            {host && <span className="story-domain">({host})</span>}
          </div>
          <div className="story-meta">
            {story.score} points by{' '}
            <a href={`/user/${story.by}`}>{story.by}</a>{' '}
            {timeAgo(story.time)} | {story.descendants ?? 0} comments
          </div>
          {story.text && (
            <div
              className="story-text"
              dangerouslySetInnerHTML={{ __html: story.text }}
            />
          )}
        </div>
        <div className="comment-section">
          {comments.length > 0 ? (
            <ul className="comment-tree">
              {comments.map((c) => (
                <CommentNode key={c.id} comment={c} depth={0} />
              ))}
            </ul>
          ) : (
            <div className="hn-empty">No comments yet.</div>
          )}
        </div>
      </main>
    </>
  );
}
